name: adapter_code_base
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  ## STATE MANAGEMENT
  get: ^4.6.5

  ## UTILS
  faker: ^2.0.0
  equatable: ^2.0.5
  lottie: ^1.4.2
  flutter_modular: ^5.0.3
  provider: ^6.0.3
  get_it: ^7.2.0
  mobx: ^2.1.0
  flutter_mobx: ^2.0.6+4
  mobx_codegen: ^2.0.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  mockito: ^5.3.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
